apiVersion: v1
kind: ReplicationController
metadata:
  name: myloginrc
spec:
  replicas: 2
  selector: 
    app: mylogin
  template: 
    metadata:
      labels:
        app: mylogin
    spec:
      containers:
        - name: mylogin-container
          image: maha4iac/myonlinebooking:2
          ports:
            - containerPort: 8080
